version: '2'
services:
  jhipsterspringangular-postgresql:
    image: postgres:11.6
    # volumes:
    #     - ~/volumes/jhipster/jhipsterSpringAngular/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${db_username}
      - POSTGRES_PASSWORD=${db_pwd}
    ports:
      - 5432:5432
